---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  namespace: monitoring 
  labels:
    service: prometheus 
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.1.0
        args:
          - "--storage.tsdb.retention=30d"
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/var/prometheus/data"
          - "--storage.tsdb.no-lockfile"          
        securityContext:
          runAsUser: 0
        ports:
          - containerPort: 9090
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus
          - name: prometheus-storage-volume
            mountPath: /var/prometheus/data
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-pv-claim
