apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter 
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: node-exporter 
subjects:
- kind: ServiceAccount
  name: node-exporter 
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
