apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: kube-system
spec:
  ports:
    - port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    k8s-app: node-exporter 
  type: NodePort
